### PR TITLE
Forbid invalid FQDN hosts

### LINKED ISSUE #354: [Bug] Invalid FQDN hosts are accepted in the Snmp Device page
Hi,

I have seen errors such as:
time="2018-06-06 11:15:31" level=error msg="Error on Name Lookup for host: xx.xx.xx.xx   ERROR: lookup xx.xx.xx.xx : no such host" 
time="2018-06-06 11:15:31" level=error msg="SNMPDEVICE [device_id] Client connect error to device  error :lookup xx.xx.xx.xx : no such host" 

This error is triggered from snmp.go/GetClient by the line:
```hostIPs, err := net.LookupHost(s.Host)```

This actually comes from an invalid FQDN name (in my case, the host value was `xx.xx.xx.xx ` with a spurious space).
I think SnmpCollector should enforce the provided FQDN host is valid, so that the call to GetClient does not trivially fail.

### PR DESCRIPTION
**Pull request by lerela**
Fixes #354

### CODE REVIEW

File: src/snmpdevice/snmpdevicecfg.component.ts [hunk 1]
```diff
@@ -118,7 +118,7 @@ export class SnmpDeviceCfgComponent {
   createStaticForm() {
     this.snmpdevForm = this.builder.group({
       ID: [this.snmpdevForm ? this.snmpdevForm.value.ID : '', Validators.required],
-      Host: [this.snmpdevForm ? this.snmpdevForm.value.Host : '', Validators.required],
+      Host: [this.snmpdevForm ? this.snmpdevForm.value.Host : '', Validators.compose([Validators.required, Validators.pattern("^([a-zA-Z0-9._-])+$")])],
```
Comment (sbengo) [inline src/snmpdevice/snmpdevicecfg.component.ts]: Instead of setting up here, would be interesting to set up as a new type into `ValidationService`  to be reusable for others components and return a message to the user (https://github.com/toni-moreno/snmpcollector/blob/master/src/common/validation.service.ts)

**Comment by sbengo** [comment]
Hi @lerela , thanks for submitting this PR!
Would be awesome if you could create a new type on ValidationService, change requested on your code

Thanks,
Regards

**Comment by lerela** [comment]
Thanks for the review @sbengo, does commit ddc883d work out for you?

**Comment by sbengo** [comment]
Thank you!
